### ISSUE TITLE
GuldenD Info CPU percentage is able to report > 100%

### ISSUE THREAD

**Issue by BramVanBerkel** [Bastijn/g-dash#27]
The CPU usage is able to report more than 100% CPU usage. Maybe because it reports the total cpu usage instead of the average usage per core?
<img width="862" alt="Screenshot 2019-10-24 at 21 40 12" src="https://user-images.githubusercontent.com/15030624/69920020-75eda000-1483-11ea-9ca3-f432aa76c028.png">

**Comment by FornaxNLG** [comment]
On Linux systems this is the common way to report CPU usage. Since a Raspberry has a quad core CPU the theoretical limit would thus be 400%.
G-Dash can be used on other machines also. If installed on a PC that is mining with 6 threads a CPU usage of about 604% would be preferable over 76% being reported.
